- name: Install MySQL 8 Repository
  yum: pkg=https://dev.mysql.com/get/mysql80-community-release-el8-2.noarch.rpm state=latest disable_gpg_check=yes
- name: Install MySQL Server
  yum:
    name: mysql-server
    state: latest
    update_cache: true
- name: Enabling MySQL at boot
  shell: systemctl enable mysqld
- name: Starting MySQL
  shell: systemctl start mysqld
